### ISSUE TITLE
当输入框被软键盘顶起时，输入框与软键盘中间出现空隙

### ISSUE THREAD

**Issue by Phyzait** [CxmyDev/screen_autosize#2]
仅试了安卓系统

页面代码
```dart
class Page extends StatelessWidget {
  Page({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(child: ListView()),
          Container(
            color: Colors.red,
            child: TextField(
              decoration: InputDecoration(hintText: 'TextField'),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by 291847424** [comment]
`class MediaQueryWrapper extends StatelessWidget {

  /// Creates a widget that delegates its build to a callback.
  ///
  /// The [builder] argument must not be null.
  const MediaQueryWrapper({
    Key key,
    @required this.builder,
  }) : assert(builder != null),
        super(key: key);

  /// Called to obtain the child widget.
  ///
  /// This function is called whenever this widget is included in its parent's
  /// build and the old widget (if any) that it synchronizes with has a distinct
  /// object identity. Typically the parent's build method will construct
  /// a new tree of widgets and so a new Builder child will not be [identical]
  /// to the corresponding old one.
  final WidgetBuilder builder;

  @override
  Widget build(BuildContext context) {
    return MediaQuery(
        data: MediaQuery.of(context).copyWith(
          textScaleFactor: 1.0,
          size: AutoSizeUtils.instance.screenSize,
          padding: AutoSizeUtils.instance.getPadding(),
          devicePixelRatio: AutoSizeUtils.instance.devicePixelRatio,
          //添加这一句
          viewInsets: EdgeInsets.fromWindowPadding(window.viewInsets, AutoSizeUtils.instance.devicePixelRatio),
        ),
        child: builder(context));
  }
}`

**Comment by 291847424** [comment]
> 仅试了安卓系统
> 
> 页面代码
> 
> ```dart
> class Page extends StatelessWidget {
>   Page({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Column(
>         children: [
>           Expanded(child: ListView()),
>           Container(
>             color: Colors.red,
>             child: TextField(
>               decoration: InputDecoration(hintText: 'TextField'),
>             ),
>           ),
>         ],
>       ),
>     );
>   }
> }
> ```

```dart
class MediaQueryWrapper extends StatelessWidget {

  /// Creates a widget that delegates its build to a callback.
  ///
  /// The [builder] argument must not be null.
  const MediaQueryWrapper({
    Key key,
    @required this.builder,
  }) : assert(builder != null),
        super(key: key);

  /// Called to obtain the child widget.
  ///
  /// This function is called whenever this widget is included in its parent's
  /// build and the old widget (if any) that it synchronizes with has a distinct
  /// object identity. Typically the parent's build method will construct
  /// a new tree of widgets and so a new Builder child will not be [identical]
  /// to the corresponding old one.
  final WidgetBuilder builder;

  @override
  Widget build(BuildContext context) {
    return MediaQuery(
        data: MediaQuery.of(context).copyWith(
          textScaleFactor: 1.0,
          size: AutoSizeUtils.instance.screenSize,
          padding: AutoSizeUtils.instance.getPadding(),
          devicePixelRatio: AutoSizeUtils.instance.devicePixelRatio,
          //添加这一句
          viewInsets: EdgeInsets.fromWindowPadding(window.viewInsets, AutoSizeUtils.instance.devicePixelRatio),
        ),
        child: builder(context));
  }
}
```
